### ISSUE TITLE
I'm unable to run this app locally

### ISSUE THREAD

**Issue by cad2222** [shwosner/realtime-chat-supabase-react#12]
I have added url and anon key from supabase but i'm getting the below error.
Uncaught TypeError: auth.user is not a function
    at Header (Header.jsx:22:13)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22776:12)
    at workLoopSync (react-dom.development.js:22707:5)

this is the error message for /auth/v1 in postman: `no Route matched with those values`

**Comment by shwosner** [comment]
The syntax in `supabase-js v2` is a little different.
```
- supabase.auth.user()
+ supabase.auth.user
```

Maybe have a look at my recent changes in [PR-18](https://github.com/shwosner/realtime-chat-supabase-react/pull/18/files#)
